version: "3.8"

services:
  api:
    build: .
    env_file:
      - ./.env

    container_name: fast-api
    ports:
      - ${APP_PORT}:8001
    volumes:
      - ./:/api # working
      # - ./api:/api # working

      # - ./api:/api
      # - ./upload-images/:/upload-images/user/

    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PG_ADMIN_PORT}:5050"
    networks:
      - postgres
    restart: unless-stopped
    # depends_on:
    #   - postgres


networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
