version: "3.8"

services:
  api:
    build: .
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    container_name: fast-api
    ports:
      - ${APP_PORT}:8001
    volumes:
      - ./:/api # working
      # - ./api:/api # working

      # - ./api:/api
      # - ./upload-images/:/upload-images/user/

    # depends_on:
    #   - db
    depends_on:
      - pgadmin
    restart: always

  # db:
  #   container_name: postgresql_db
  #   env_file:
  #     - .env
  #   image: postgres
  #   restart: always
  #   ports:
  #     - ${DB_PORT}:5432
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_DATABASE}

  pgadmin:
    container_name: pgadmin
    env_file:
      - .env
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PG_ADMIN_PORT}:5050
    # depends_on:
    #   - db
